name: "Version Next"
description: "This software automatically calculates the next version from an array of semantic versioning strings, following SemVer rules."
author: "niwaniwa"
# version=1.0.0

inputs:
  version-input:
    description: "An array of semantic versioning strings (e.g., 2.3.1, 2.4.0-rc.1, 2.3.2-beta.1) "
    required: true
    default: ""
  release-type:
    type: choice
    description: "The type of release (none, alpha, beta, rc, or release)"
    required: false
    default: "none"
    options:
      - none
      - alpha
      - beta
      - rc
      - release

runs:
  using: "composite"
  steps:
    - name: clone
      run: |
        git clone git@github.com:niwaniwa/version-next.git
        cd version-next
        go build -ldflags="-s -w" -o ${{ github.action_path }}/version-next main.go
      shell: bash

    - name: run
      run: |
        if [ "${{ inputs.release-type }}" != "none" ]; then
          ${{ github.action_path }}/version-next -v ${{ inputs.version-input }} -r ${{ inputs.release-type }}
        else
          ${{ github.action_path }}/version-next -v ${{ inputs.version-input }}
        fi
      shell: bash
