name: "Version Next"
description: "This software automatically calculates the next version from an array of semantic versioning strings, following SemVer rules."
author: "niwaniwa"
# version=1.0.0

inputs:
  version-input:
    description: "An array of semantic versioning strings (e.g., 2.3.1, 2.4.0-rc.1, 2.3.2-beta.1) "
    required: true
    default: ""
  release-type:
    description: "The type of release (alpha, beta, rc, or release)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: clone
      run: |
        git clone https://github.com/niwaniwa/VersionNext.git
        cd VersionNext
        go build -ldflags="-s -w" -o ${{ github.action_path }}/VersionNext main.go
      shell: bash

    - name: run
      run: |
        if [ -n "${{ inputs.release-type }}" ]; then
          ${{ github.action_path }}/VersionNext -v ${{ inputs.version-input }} -r ${{ inputs.release-type }}
        else
          ${{ github.action_path }}/VersionNext -v ${{ inputs.version-input }}
        fi
      shell: bash
